/**
 * Jungle theme — centralized asset keys and source paths.
 *
 * Assets live under `public/` so paths are root-relative at runtime.
 * The later theme system will read from a shape like this, so reskinning
 * means swapping this file (+ art) without touching scene logic.
 */
export const JungleTheme = {
  key: 'jungle',
  assets: {
    cover: { key: 'cover', path: 'game_ui/cover.png' },
    playButton: { key: 'play_button', path: 'game_ui/play_button.png' },
    // Only layers 1 & 2 are background art. Layer 3 is reserved for the
    // gameplay foreground (player + hooks/vines), added in a later phase.
    background: [
      { key: 'bg_layer_1', path: 'background_layers/layer_1_background.png' },
      { key: 'bg_layer_2', path: 'background_layers/layer_2_background.png' },
    ],
    // surfaceRatio = where the stone slab's top surface sits within the image
    // (measured: y≈386 / 1024) — used to plant the character on the slab.
    platform: {
      key: 'starting_point',
      path: 'platform/starting_point.png',
      surfaceRatio: 0.377,
    },
    // The overhead beam that runs along the top of the level. Hooks/vines will
    // hang from it. woodBottomRatio = where the wood band ends within the image
    // (measured: opaque rows 402–528 of 941) so we can sit it flush at the top.
    overheadBar: {
      key: 'wooden_bar',
      path: 'platform/wooden_bar.png',
      woodTopRatio: 0.427,
      woodBottomRatio: 0.561,
    },
    // The wooden ring hook the character ropes onto to swing. Square image.
    hook: { key: 'wooden_circle', path: 'platform/wooden_circle.png' },
    // Aligned idle sheet generated by scripts/realign-spritesheet.cjs from the
    // original strip — every frame is centered & feet-aligned so it animates
    // in place (no left-right drift).
    characterIdle: {
      key: 'character_idle',
      path: 'character/character_idle_aligned.png',
      frameWidth: 355,
      frameHeight: 625,
      frameCount: 4,
      feetOriginY: 0.9632,
      bodyTopY: 34,
      bodyHeight: 568,
    },
    // Leaping/jump sheet (1774×887, 4 frames). We currently use only frame 0 as
    // the jump pose. frame 0: feet at y≈625/887, body height ~381px.
    characterJump: {
      key: 'character_jump',
      path: 'character/character_jumping_spirit_sheet.png',
      frameWidth: 443,
      frameHeight: 887,
      frameCount: 4,
      feetOriginY: 0.7046,
      bodyHeight: 381,
    },
    // Hanging sheet (2172×724, 3 frames → 724×724). We use frame 1 (one arm
    // raised, gripping). The raised hand is the grab point: measured at
    // x≈0.499, y≈0.152 of the frame — used as the origin so the hand sits on
    // the rope's top end. Body spans y 110–627 (bodyHeight ~517).
    characterHang: {
      key: 'character_hang',
      path: 'character/character_hanging_spirit_sheet.png',
      frameWidth: 724,
      frameHeight: 724,
      frameCount: 3,
      hangFrame: 1,
      handOriginX: 0.499,
      handOriginY: 0.152,
      bodyHeight: 517,
    },
  },
} as const

export type ThemeAssets = typeof JungleTheme.assets
