/**
 * Jungle theme — centralized asset keys and source paths.
 *
 * Assets live under `public/` so paths are root-relative at runtime.
 * The later theme system will read from a shape like this, so reskinning
 * means swapping this file (+ art) without touching scene logic.
 */
export const JungleTheme = {
  key: 'jungle',
  assets: {
    cover: { key: 'cover', path: 'game_ui/cover.png' },
    playButton: { key: 'play_button', path: 'game_ui/play_button.png' },
    retryButton: { key: 'retry_button', path: 'game_ui/retry_button.png' },
    campaignButton: { key: 'campaign_button', path: 'game_ui/campaign_button.png' },
    endlessButton: { key: 'endless_button', path: 'game_ui/endless_button.png' },
    // In-game home icon + its confirm-dialog buttons (GO HOME / STAY).
    homeButton: { key: 'home_button', path: 'game_ui/home_button.png' },
    homeTextButton: { key: 'home_text_button', path: 'game_ui/home_text_button.png' },
    stayButton: { key: 'stay_button', path: 'game_ui/stay_button.png' },
    // SFX played when the character launches off the starting platform.
    jumpSound: { key: 'jump_sound', path: 'sound_effects/jump_sound.ogg' },
    // SFX played when the character releases the rope to fly off a hook. Several
    // variants are cycled in order on successive releases so it doesn't get
    // repetitive (see GameScene.sfxRelease).
    ropeReleaseSounds: [
      { key: 'rope_release_sound', path: 'sound_effects/rope_release_sound.mp3' },
      { key: 'rope_release_sound_2', path: 'sound_effects/rope_release_sound_2.mp3' },
      { key: 'rope_release_sound_3', path: 'sound_effects/rope_release_sound_3.mp3' },
      { key: 'rope_release_sound_4', path: 'sound_effects/rope_release_sound_4.mp3' },
    ],
    // Only layers 1 & 2 are background art. Layer 3 is reserved for the
    // gameplay foreground (player + hooks/vines), added in a later phase.
    background: [
      { key: 'bg_layer_1', path: 'background_layers/layer_1_background.png' },
      { key: 'bg_layer_2', path: 'background_layers/layer_2_background.png' },
    ],
    // surfaceRatio = where the stone slab's top surface sits within the image
    // (measured: y≈386 / 1024) — used to plant the character on the slab.
    platform: {
      key: 'starting_point',
      path: 'platform/starting_point.png',
      surfaceRatio: 0.377,
    },
    // The overhead beam that runs along the top of the level. Hooks/vines will
    // hang from it. woodBottomRatio = where the wood band ends within the image
    // (measured: opaque rows 402–528 of 941) so we can sit it flush at the top.
    overheadBar: {
      key: 'wooden_bar',
      path: 'platform/wooden_bar.png',
      woodTopRatio: 0.427,
      woodBottomRatio: 0.561,
    },
    // The wooden ring hook the character ropes onto to swing. Square image.
    hook: { key: 'wooden_circle', path: 'platform/wooden_circle.png' },
    // The collectible banana scattered through the level.
    banana: { key: 'banana', path: 'platform/banana.png' },
    // The swing rope vine (724×2172, vertical, core centered, uniform → stretchable).
    // Drawn from the hook down to the character's hands while swinging.
    rope: { key: 'rope', path: 'platform/rope.png' },
    // The goal temple at the far end of the level (1086×1448, transparent, GOAL
    // flag, front-facing). The character lands on the front ledge in front of the
    // glowing entrance. landingXRatio = centered (0.5); landingSurfaceRatio = the
    // ledge top surface (~0.5 of image height). Measured from the art.
    destination: {
      key: 'destination',
      path: 'platform/destination_point.png',
      landingSurfaceRatio: 0.5,
      landingXRatio: 0.5,
    },
    // Aligned idle sheet generated by scripts/realign-spritesheet.cjs from the
    // original strip — every frame is centered & feet-aligned so it animates
    // in place (no left-right drift).
    characterIdle: {
      key: 'character_idle',
      path: 'character/character_idle_aligned.png',
      frameWidth: 355,
      frameHeight: 625,
      frameCount: 4,
      feetOriginY: 0.9632,
      bodyTopY: 34,
      bodyHeight: 568,
    },
    // Jump/leap sheet — first 3 frames of the run→leap sequence, feet-aligned by
    // scripts/align-feet-sheet.cjs. Played once on launch, then holds the last
    // frame while airborne.
    characterJump: {
      key: 'character_jump',
      path: 'character/character_jump_aligned.png',
      frameWidth: 388,
      frameHeight: 354,
      frameCount: 3,
      feetOriginY: 0.9548,
      bodyHeight: 322,
    },
    // Landing sheet — frames 3 & 4 of the jump source (extended leap → reach),
    // feet-aligned by scripts/align-feet-sheet.cjs. Plays once on touchdown.
    characterLand: {
      key: 'character_land',
      path: 'character/character_land_aligned.png',
      frameWidth: 388,
      frameHeight: 361,
      frameCount: 2,
      feetOriginY: 0.9557,
      bodyHeight: 329,
    },
    // Swing sheets, hand-aligned by scripts/align-swing-sheet.cjs so the raised
    // hands sit at the same top-center anchor in every frame. Origin = that hand
    // point, placed on the rope's end → hands stay locked on the rope while the
    // body swings below. Forward = swinging in the travel direction; backward =
    // swinging back.
    characterSwingForward: {
      key: 'character_swing_fwd',
      path: 'character/character_swing_forward_aligned.png',
      frameWidth: 368,
      frameHeight: 423,
      frameCount: 2,
      handOriginX: 0.5,
      handOriginY: 0.0449,
      bodyHeight: 374,
    },
    characterSwingBackward: {
      key: 'character_swing_back',
      path: 'character/character_swing_backward_aligned.png',
      frameWidth: 572,
      frameHeight: 479,
      frameCount: 3,
      handOriginX: 0.5,
      handOriginY: 0.0438,
      bodyHeight: 424,
    },
  },
} as const

export type ThemeAssets = typeof JungleTheme.assets
