/**
 * Jungle theme — centralized asset keys and source paths.
 *
 * Assets live under `public/` so paths are root-relative at runtime.
 * The later theme system will read from a shape like this, so reskinning
 * means swapping this file (+ art) without touching scene logic.
 */
export const JungleTheme = {
  key: 'jungle',
  assets: {
    cover: { key: 'cover', path: 'game_ui/cover.png' },
    playButton: { key: 'play_button', path: 'game_ui/play_button.png' },
    // Only layers 1 & 2 are background art. Layer 3 is reserved for the
    // gameplay foreground (player + hooks/vines), added in a later phase.
    background: [
      { key: 'bg_layer_1', path: 'background_layers/layer_1_background.png' },
      { key: 'bg_layer_2', path: 'background_layers/layer_2_background.png' },
    ],
    // surfaceRatio = where the stone slab's top surface sits within the image
    // (measured: y≈386 / 1024) — used to plant the character on the slab.
    platform: {
      key: 'starting_point',
      path: 'platform/starting_point.png',
      surfaceRatio: 0.377,
    },
    // The overhead beam that runs along the top of the level. Hooks/vines will
    // hang from it. woodBottomRatio = where the wood band ends within the image
    // (measured: opaque rows 402–528 of 941) so we can sit it flush at the top.
    overheadBar: {
      key: 'wooden_bar',
      path: 'platform/wooden_bar.png',
      woodTopRatio: 0.427,
      woodBottomRatio: 0.561,
    },
    // The wooden ring hook the character ropes onto to swing. Square image.
    hook: { key: 'wooden_circle', path: 'platform/wooden_circle.png' },
    // Aligned idle sheet generated by scripts/realign-spritesheet.cjs from the
    // original strip — every frame is centered & feet-aligned so it animates
    // in place (no left-right drift).
    characterIdle: {
      key: 'character_idle',
      path: 'character/character_idle_aligned.png',
      frameWidth: 355,
      frameHeight: 625,
      frameCount: 4,
      feetOriginY: 0.9632,
      bodyTopY: 34,
      bodyHeight: 568,
    },
    // Jump/leap sheet — first 3 frames of the run→leap sequence, feet-aligned by
    // scripts/align-feet-sheet.cjs. Played once on launch, then holds the last
    // frame while airborne.
    characterJump: {
      key: 'character_jump',
      path: 'character/character_jump_aligned.png',
      frameWidth: 388,
      frameHeight: 355,
      frameCount: 3,
      feetOriginY: 0.9549,
      bodyHeight: 323,
    },
    // Swing sheets, hand-aligned by scripts/align-swing-sheet.cjs so the raised
    // hands sit at the same top-center anchor in every frame. Origin = that hand
    // point, placed on the rope's end → hands stay locked on the rope while the
    // body swings below. Forward = swinging in the travel direction; backward =
    // swinging back.
    characterSwingForward: {
      key: 'character_swing_fwd',
      path: 'character/character_swing_forward_aligned.png',
      frameWidth: 368,
      frameHeight: 423,
      frameCount: 2,
      handOriginX: 0.5,
      handOriginY: 0.0449,
      bodyHeight: 374,
    },
    characterSwingBackward: {
      key: 'character_swing_back',
      path: 'character/character_swing_backward_aligned.png',
      frameWidth: 572,
      frameHeight: 479,
      frameCount: 3,
      handOriginX: 0.5,
      handOriginY: 0.0438,
      bodyHeight: 424,
    },
  },
} as const

export type ThemeAssets = typeof JungleTheme.assets
